version: '3.8'

services:
  app:
    container_name: operation-dashboard-prod
    image: operation-dashboard
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_ENV=PROD
        - REACT_APP_BASE_URL=https://dashboard.asklora.store/api/v1
        - REACT_APP_URL='operation-dashboard'
    ports:
      - 8080:80
